# Generated by Django 5.2.9 on 2026-02-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('summary', models.CharField(help_text='A one-sentence hook - shows on homepage if featured', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_recipient_1', models.EmailField(blank=True, help_text='Optional: Send applications for this job here instead of the master email.', max_length=254, null=True)),
                ('custom_recipient_2', models.EmailField(blank=True, help_text='Optional: A second email to receive applications for this job.', max_length=254, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_shared_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='customers.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(editable=False, max_length=63, null=True, unique=True)),
                ('template_choice', models.CharField(choices=[('executive', 'The Executive'), ('startup', 'The Startup'), ('boutique', 'The Boutique')], default='executive', max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Your logo (appears in navigation bar)', null=True, upload_to='logos/')),
                ('primary_color', models.CharField(default='#1e3a8a', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('hero_title', models.CharField(default='Great Careers Await', max_length=200)),
                ('hero_text', models.TextField(blank=True, help_text='The main pitch to candidates')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('about_title', models.CharField(blank=True, default='Our Story', max_length=200)),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('about_content', models.TextField(blank=True)),
                ('jobs_header_text', models.TextField(blank=True, default='Explore our current openings.')),
                ('contact_email', models.EmailField(blank=True, help_text='General enquiries email', max_length=200)),
                ('contact_phone', models.CharField(blank=True, help_text='Main contact number', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Full office address for the footer')),
                ('master_application_email', models.EmailField(blank=True, help_text="The default email for applications if a job doesn't have a specific recipient set.", max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('featured_job', models.ForeignKey(blank=True, help_text='Choose a job to feature on your homepage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_profile', to='cms.job')),
            ],
        ),
    ]
