# Generated by Django 5.2.9 on 2026-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='homepage_body_text',
            field=models.TextField(blank=True, help_text='Short paragraph shown below the hero section on the homepage.'),
        ),
    ]
