# Generated by Django 5.2.9 on 2026-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='primary_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='secondary_color',
            field=models.CharField(default='#0f172a', max_length=7),
        ),
    ]
