# Generated by Django 5.2.9 on 2026-02-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_companyprofile_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tenant',
        ),
    ]
