# Generated by Django 5.2.9 on 2026-02-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_companyprofile_homepage_body_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='master_application_email',
        ),
    ]
