# Generated by Django 5.2.9 on 2026-02-10 15:29

import datetime
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('template_choice', models.CharField(choices=[('executive', 'The Executive'), ('startup', 'The Startup'), ('boutique', 'The Boutique')], default='executive', max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('notification_email_1', models.EmailField(blank=True, max_length=255, null=True)),
                ('notification_email_2', models.EmailField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('dummy_field', models.BooleanField(default=False)),
                ('dummy_field2', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=50)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100)),
                ('max_jobs', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='customers.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.plan'),
        ),
    ]
