# Generated by Django 5.2.9 on 2026-02-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dummy_field2',
        ),
    ]
