# Generated by Django 5.2.9 on 2026-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_client_dummy_field_remove_client_dummy_field2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='master_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
